1ST TASK

Newton Second Law

SET m = 600
SET a = 2
SET F = m * a
DISPLAY F



2ND TASK

Tahun Kabisat

SET T = NUMBER
SET K = ('KABISAT')
  IF T%4 == 0 AND T%100 !== 0
  THEN T = K
  IF ELSE T%4 == 0 AND T%100 == 0 AND T%400 == 0
  THEN T = K

  END IF


3RD TASK

Laundry Day

SET P = NUMBER
SET M = 'MESIN CUCI'
  IF P = 20 THEN M ON
  ELSE M OFF

END IF


4TH TASK

Periksa Kuku

SET S = 40
SET K = TRUE
SET H = TRUE

  IF K = TRUE THEN H = TRUE
  ELSE K != TRUE THEN H !=TRUE

END IF
